// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package rest

import (
	"net/http"

	"github.com/go-openapi/swag"
	"github.com/sirupsen/logrus"
	"github.com/zergslaw/users/internal/api/rest/generated/models"
	"github.com/zergslaw/users/internal/api/rest/generated/restapi/operations"
	"github.com/zergslaw/users/internal/log"
)

//nolint:dupl,goconst
func errLogin(logger logrus.FieldLogger, err error, code int) operations.LoginResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewLoginDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}

//nolint:dupl,goconst
func errLogout(logger logrus.FieldLogger, err error, code int) operations.LogoutResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewLogoutDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}

//nolint:dupl,goconst
func errVerificationEmail(logger logrus.FieldLogger, err error, code int) operations.VerificationEmailResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewVerificationEmailDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}

//nolint:dupl,goconst
func errVerificationUsername(logger logrus.FieldLogger, err error, code int) operations.VerificationUsernameResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewVerificationUsernameDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}

//nolint:dupl,goconst
func errGetUser(logger logrus.FieldLogger, err error, code int) operations.GetUserResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewGetUserDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}

//nolint:dupl,goconst
func errDeleteUser(logger logrus.FieldLogger, err error, code int) operations.DeleteUserResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewDeleteUserDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}

//nolint:dupl,goconst
func errUpdatePassword(logger logrus.FieldLogger, err error, code int) operations.UpdatePasswordResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewUpdatePasswordDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}

//nolint:dupl,goconst
func errUpdateUsername(logger logrus.FieldLogger, err error, code int) operations.UpdateUsernameResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewUpdateUsernameDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}

//nolint:dupl,goconst
func errUpdateEmail(logger logrus.FieldLogger, err error, code int) operations.UpdateEmailResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewUpdateEmailDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}

//nolint:dupl,goconst
func errGetUsers(logger logrus.FieldLogger, err error, code int) operations.GetUsersResponder { //nolint:deadcode,unused
	if code < http.StatusInternalServerError {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "client"}).Info(err)
	} else {
		logger.WithFields(logrus.Fields{log.HTTPStatus: code, log.Error: "server"}).Warn(err)
	}

	msg := err.Error()
	if code == http.StatusInternalServerError { // Do no expose details about internal errors.
		msg = "internal error"
	}

	return operations.NewGetUsersDefault(code).WithPayload(&models.Error{Message: swag.String(msg)})
}
