run:
  tests: false
  skip-dirs:
    - generated
    - mock
    - migration

linters-settings:
  lll:
    line-length: 150
  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable:
    - dupl
    - wsl
    - nolintlint
    - gomnd
  fast: false

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoglobals
    - path: internal/metrics/
      linters:
        - gochecknoglobals
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - gochecknoglobals
      source: "var metric "