version: '3.7'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB:  "postgres"
      POSTGRES_PASSWORD: "postgres"

  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    image: boilerplate
    container_name: boilerplate
    restart: always
    command: "./boilerplate serve --jwt-key testKey --db-host postgres --operation up"
    ports:
      - "8080:8080"
