version: '3.7'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB:  "postgres"
      POSTGRES_PASSWORD: "postgres"

  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    image: boilerplate
    container_name: boilerplate
    restart: always
    command: >
      sh -c "./boilerplate migrate --dir migrate --operation up --db-host postgres &&
             ./boilerplate serve --web-port 8080 --jwt-key testKey --db-host postgres"
    environment:
      EMAIL_API_KEY: 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
      EMAIL_FROM: test@test.com
    ports:
      - "8080:8080"
