version: '3.7'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: postgres

#  users:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: users
#    container_name: users
#    restart: always
#    command: "./users serve --jwt-key testKey --db-host postgres --migrate up"
#    ports:
#      - "8080:8080"
