// Code generated by "stringer --type MessageKind"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Welcome-1]
	_ = x[ChangeEmail-2]
	_ = x[PassRecovery-3]
}

const _MessageKind_name = "WelcomeChangeEmailPassRecovery"

var _MessageKind_index = [...]uint8{0, 7, 18, 30}

func (i MessageKind) String() string {
	i -= 1
	if i < 0 || i >= MessageKind(len(_MessageKind_index)-1) {
		return "MessageKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageKind_name[_MessageKind_index[i]:_MessageKind_index[i+1]]
}
