// Code generated by MockGen. DO NOT EDIT.
// Source: ../app/app.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	app "github.com/zergslaw/users/internal/app"
	reflect "reflect"
	time "time"
)

// Repo is a mock of Repo interface
type Repo struct {
	ctrl     *gomock.Controller
	recorder *RepoMockRecorder
}

// RepoMockRecorder is the mock recorder for Repo
type RepoMockRecorder struct {
	mock *Repo
}

// NewRepo creates a new mock instance
func NewRepo(ctrl *gomock.Controller) *Repo {
	mock := &Repo{ctrl: ctrl}
	mock.recorder = &RepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Repo) EXPECT() *RepoMockRecorder {
	return m.recorder
}

// CreateUser mocks base method
func (m *Repo) CreateUser(arg0 context.Context, arg1 app.User) (app.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(app.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser
func (mr *RepoMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*Repo)(nil).CreateUser), arg0, arg1)
}

// DeleteUser mocks base method
func (m *Repo) DeleteUser(arg0 context.Context, arg1 app.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser
func (mr *RepoMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*Repo)(nil).DeleteUser), arg0, arg1)
}

// UpdateUsername mocks base method
func (m *Repo) UpdateUsername(arg0 context.Context, arg1 app.UserID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsername", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsername indicates an expected call of UpdateUsername
func (mr *RepoMockRecorder) UpdateUsername(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsername", reflect.TypeOf((*Repo)(nil).UpdateUsername), arg0, arg1, arg2)
}

// UpdateEmail mocks base method
func (m *Repo) UpdateEmail(arg0 context.Context, arg1 app.UserID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail
func (mr *RepoMockRecorder) UpdateEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*Repo)(nil).UpdateEmail), arg0, arg1, arg2)
}

// UpdatePassword mocks base method
func (m *Repo) UpdatePassword(arg0 context.Context, arg1 app.UserID, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword
func (mr *RepoMockRecorder) UpdatePassword(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*Repo)(nil).UpdatePassword), arg0, arg1, arg2)
}

// UserByID mocks base method
func (m *Repo) UserByID(arg0 context.Context, arg1 app.UserID) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", arg0, arg1)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID
func (mr *RepoMockRecorder) UserByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*Repo)(nil).UserByID), arg0, arg1)
}

// UserByTokenID mocks base method
func (m *Repo) UserByTokenID(arg0 context.Context, arg1 app.TokenID) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByTokenID", arg0, arg1)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByTokenID indicates an expected call of UserByTokenID
func (mr *RepoMockRecorder) UserByTokenID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByTokenID", reflect.TypeOf((*Repo)(nil).UserByTokenID), arg0, arg1)
}

// UserByEmail mocks base method
func (m *Repo) UserByEmail(arg0 context.Context, arg1 string) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByEmail", arg0, arg1)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByEmail indicates an expected call of UserByEmail
func (mr *RepoMockRecorder) UserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByEmail", reflect.TypeOf((*Repo)(nil).UserByEmail), arg0, arg1)
}

// UserByUsername mocks base method
func (m *Repo) UserByUsername(arg0 context.Context, arg1 string) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByUsername indicates an expected call of UserByUsername
func (mr *RepoMockRecorder) UserByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByUsername", reflect.TypeOf((*Repo)(nil).UserByUsername), arg0, arg1)
}

// ListUserByUsername mocks base method
func (m *Repo) ListUserByUsername(arg0 context.Context, arg1 string, arg2 app.Page) ([]app.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserByUsername", arg0, arg1, arg2)
	ret0, _ := ret[0].([]app.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUserByUsername indicates an expected call of ListUserByUsername
func (mr *RepoMockRecorder) ListUserByUsername(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserByUsername", reflect.TypeOf((*Repo)(nil).ListUserByUsername), arg0, arg1, arg2)
}

// SaveSession mocks base method
func (m *Repo) SaveSession(arg0 context.Context, arg1 app.UserID, arg2 app.TokenID, arg3 app.Origin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession
func (mr *RepoMockRecorder) SaveSession(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*Repo)(nil).SaveSession), arg0, arg1, arg2, arg3)
}

// SessionByTokenID mocks base method
func (m *Repo) SessionByTokenID(arg0 context.Context, arg1 app.TokenID) (*app.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionByTokenID", arg0, arg1)
	ret0, _ := ret[0].(*app.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionByTokenID indicates an expected call of SessionByTokenID
func (mr *RepoMockRecorder) SessionByTokenID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionByTokenID", reflect.TypeOf((*Repo)(nil).SessionByTokenID), arg0, arg1)
}

// DeleteSession mocks base method
func (m *Repo) DeleteSession(arg0 context.Context, arg1 app.TokenID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession
func (mr *RepoMockRecorder) DeleteSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*Repo)(nil).DeleteSession), arg0, arg1)
}

// Notification is a mock of Notification interface
type Notification struct {
	ctrl     *gomock.Controller
	recorder *NotificationMockRecorder
}

// NotificationMockRecorder is the mock recorder for Notification
type NotificationMockRecorder struct {
	mock *Notification
}

// NewNotification creates a new mock instance
func NewNotification(ctrl *gomock.Controller) *Notification {
	mock := &Notification{ctrl: ctrl}
	mock.recorder = &NotificationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Notification) EXPECT() *NotificationMockRecorder {
	return m.recorder
}

// Notification mocks base method
func (m *Notification) Notification(contact string, msg app.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notification", contact, msg)
}

// Notification indicates an expected call of Notification
func (mr *NotificationMockRecorder) Notification(contact, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notification", reflect.TypeOf((*Notification)(nil).Notification), contact, msg)
}

// Password is a mock of Password interface
type Password struct {
	ctrl     *gomock.Controller
	recorder *PasswordMockRecorder
}

// PasswordMockRecorder is the mock recorder for Password
type PasswordMockRecorder struct {
	mock *Password
}

// NewPassword creates a new mock instance
func NewPassword(ctrl *gomock.Controller) *Password {
	mock := &Password{ctrl: ctrl}
	mock.recorder = &PasswordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Password) EXPECT() *PasswordMockRecorder {
	return m.recorder
}

// Hashing mocks base method
func (m *Password) Hashing(password string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hashing", password)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hashing indicates an expected call of Hashing
func (mr *PasswordMockRecorder) Hashing(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hashing", reflect.TypeOf((*Password)(nil).Hashing), password)
}

// Compare mocks base method
func (m *Password) Compare(hashedPassword, password []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", hashedPassword, password)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Compare indicates an expected call of Compare
func (mr *PasswordMockRecorder) Compare(hashedPassword, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*Password)(nil).Compare), hashedPassword, password)
}

// Auth is a mock of Auth interface
type Auth struct {
	ctrl     *gomock.Controller
	recorder *AuthMockRecorder
}

// AuthMockRecorder is the mock recorder for Auth
type AuthMockRecorder struct {
	mock *Auth
}

// NewAuth creates a new mock instance
func NewAuth(ctrl *gomock.Controller) *Auth {
	mock := &Auth{ctrl: ctrl}
	mock.recorder = &AuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Auth) EXPECT() *AuthMockRecorder {
	return m.recorder
}

// Token mocks base method
func (m *Auth) Token(expired time.Duration) (app.AuthToken, app.TokenID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token", expired)
	ret0, _ := ret[0].(app.AuthToken)
	ret1, _ := ret[1].(app.TokenID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Token indicates an expected call of Token
func (mr *AuthMockRecorder) Token(expired interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*Auth)(nil).Token), expired)
}

// Parse mocks base method
func (m *Auth) Parse(token app.AuthToken) (app.TokenID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", token)
	ret0, _ := ret[0].(app.TokenID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse
func (mr *AuthMockRecorder) Parse(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*Auth)(nil).Parse), token)
}

// OAuth is a mock of OAuth interface
type OAuth struct {
	ctrl     *gomock.Controller
	recorder *OAuthMockRecorder
}

// OAuthMockRecorder is the mock recorder for OAuth
type OAuthMockRecorder struct {
	mock *OAuth
}

// NewOAuth creates a new mock instance
func NewOAuth(ctrl *gomock.Controller) *OAuth {
	mock := &OAuth{ctrl: ctrl}
	mock.recorder = &OAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *OAuth) EXPECT() *OAuthMockRecorder {
	return m.recorder
}

// Account mocks base method
func (m *OAuth) Account(arg0 context.Context, arg1 string) (*app.OAuthAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Account", arg0, arg1)
	ret0, _ := ret[0].(*app.OAuthAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Account indicates an expected call of Account
func (mr *OAuthMockRecorder) Account(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Account", reflect.TypeOf((*OAuth)(nil).Account), arg0, arg1)
}

// App is a mock of App interface
type App struct {
	ctrl     *gomock.Controller
	recorder *AppMockRecorder
}

// AppMockRecorder is the mock recorder for App
type AppMockRecorder struct {
	mock *App
}

// NewApp creates a new mock instance
func NewApp(ctrl *gomock.Controller) *App {
	mock := &App{ctrl: ctrl}
	mock.recorder = &AppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *App) EXPECT() *AppMockRecorder {
	return m.recorder
}

// VerificationEmail mocks base method
func (m *App) VerificationEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerificationEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerificationEmail indicates an expected call of VerificationEmail
func (mr *AppMockRecorder) VerificationEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerificationEmail", reflect.TypeOf((*App)(nil).VerificationEmail), ctx, email)
}

// VerificationUsername mocks base method
func (m *App) VerificationUsername(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerificationUsername", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerificationUsername indicates an expected call of VerificationUsername
func (mr *AppMockRecorder) VerificationUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerificationUsername", reflect.TypeOf((*App)(nil).VerificationUsername), ctx, username)
}

// Login mocks base method
func (m *App) Login(ctx context.Context, email, password string, origin app.Origin) (*app.User, app.AuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password, origin)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(app.AuthToken)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login
func (mr *AppMockRecorder) Login(ctx, email, password, origin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*App)(nil).Login), ctx, email, password, origin)
}

// Logout mocks base method
func (m *App) Logout(arg0 context.Context, arg1 app.AuthUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout
func (mr *AppMockRecorder) Logout(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*App)(nil).Logout), arg0, arg1)
}

// CreateUser mocks base method
func (m *App) CreateUser(ctx context.Context, email, username, password string, origin app.Origin) (*app.User, app.AuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, email, username, password, origin)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(app.AuthToken)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateUser indicates an expected call of CreateUser
func (mr *AppMockRecorder) CreateUser(ctx, email, username, password, origin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*App)(nil).CreateUser), ctx, email, username, password, origin)
}

// User mocks base method
func (m *App) User(arg0 context.Context, arg1 app.UserID) (*app.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", arg0, arg1)
	ret0, _ := ret[0].(*app.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User
func (mr *AppMockRecorder) User(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*App)(nil).User), arg0, arg1)
}

// UserByAuthToken mocks base method
func (m *App) UserByAuthToken(ctx context.Context, token app.AuthToken) (*app.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByAuthToken", ctx, token)
	ret0, _ := ret[0].(*app.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByAuthToken indicates an expected call of UserByAuthToken
func (mr *AppMockRecorder) UserByAuthToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByAuthToken", reflect.TypeOf((*App)(nil).UserByAuthToken), ctx, token)
}

// DeleteUser mocks base method
func (m *App) DeleteUser(arg0 context.Context, arg1 app.AuthUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser
func (mr *AppMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*App)(nil).DeleteUser), arg0, arg1)
}

// UpdateUsername mocks base method
func (m *App) UpdateUsername(arg0 context.Context, arg1 app.AuthUser, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsername", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsername indicates an expected call of UpdateUsername
func (mr *AppMockRecorder) UpdateUsername(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsername", reflect.TypeOf((*App)(nil).UpdateUsername), arg0, arg1, arg2)
}

// UpdateEmail mocks base method
func (m *App) UpdateEmail(arg0 context.Context, arg1 app.AuthUser, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail
func (mr *AppMockRecorder) UpdateEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*App)(nil).UpdateEmail), arg0, arg1, arg2)
}

// UpdatePassword mocks base method
func (m *App) UpdatePassword(ctx context.Context, authUser app.AuthUser, oldPass, newPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, authUser, oldPass, newPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword
func (mr *AppMockRecorder) UpdatePassword(ctx, authUser, oldPass, newPass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*App)(nil).UpdatePassword), ctx, authUser, oldPass, newPass)
}

// ListUserByUsername mocks base method
func (m *App) ListUserByUsername(arg0 context.Context, arg1 app.AuthUser, arg2 string, arg3 app.Page) ([]app.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserByUsername", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]app.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUserByUsername indicates an expected call of ListUserByUsername
func (mr *AppMockRecorder) ListUserByUsername(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserByUsername", reflect.TypeOf((*App)(nil).ListUserByUsername), arg0, arg1, arg2, arg3)
}
