name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.14.
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Install golangci-lint.
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin latest

      - name: Start linter.
        run: make lint
