name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.14.
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt

      - name: Start test.
        run: make test
