name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.14.
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Start test.
        run: make test
